version: '3.9'
services:
   identity_db_pg:
      container_name: identity_db_pg
      image: postgres:12-alpine
      restart: unless-stopped
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=postgres
      ports:
         - 5432:5432
      networks:
         - default
networks:
   default:
      name: identity_net_pg