version: '3.9'
services:
   identity_db_mssql:
      container_name: identity_db_mssql
      image: mcr.microsoft.com/mssql/server:2019-CU9-ubuntu-18.04
      restart: unless-stopped
      environment:
         - SA_PASSWORD=P@ssword123!
         - ACCEPT_EULA=y
         - MSSQL_PID=Express
      ports:
         - 1433:1433
      networks:
         - default
networks:
   default:
      name: identity_net_mssql